name: 18 - Inyección de código
on:
  issues: 
    types:
      - opened
jobs:
  inyeccion:
    runs-on: ubuntu-latest
    steps:
      - run: |
          title="${{ github.event.issues.title }} "
          echo ${ISSUE_TITLE}
          